name: dev
url: https://disease-community-frontend-dev-508246122017.asia-northeast1.run.app
protection_rules:
  - type: required_reviewers
    required_reviewers: 0
  - type: wait_timer
    wait_timer: 0
