name: production
url: https://disease-community-frontend-508246122017.asia-northeast1.run.app
protection_rules:
  - type: required_reviewers
    required_reviewers: 2
  - type: wait_timer
    wait_timer: 10
  - type: branch_policy
    branch_policy:
      branch_name_pattern: main
