name: staging
url: https://disease-community-frontend-staging-508246122017.asia-northeast1.run.app
protection_rules:
  - type: required_reviewers
    required_reviewers: 1
  - type: wait_timer
    wait_timer: 5
