"""Add disease management tables

Revision ID: 2b640183f173
Revises: 86db3e3cb5f3
Create Date: 2025-10-20 00:17:56.742720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b640183f173'
down_revision: Union[str, None] = '86db3e3cb5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_locale_name_formats_id'), 'locale_name_formats', ['id'], unique=False)
    op.create_index(op.f('ix_name_display_orders_id'), 'name_display_orders', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_id'), 'user_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_member_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_nickname_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_nickname_key'), 'users', ['nickname'])
    op.create_unique_constraint(op.f('users_member_id_key'), 'users', ['member_id'])
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_activity_logs_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_name_display_orders_id'), table_name='name_display_orders')
    op.drop_index(op.f('ix_locale_name_formats_id'), table_name='locale_name_formats')
    # ### end Alembic commands ###
